version: "3.8"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
